print("Welcome to our story about happiness! This will be a text-heavy game. Are you ready to start?")
user_input = input()
while user_input != "yes":
    user_input = input()
    print("That's fine. Simply type 'yes' when you are ready.")
print("You smile and breathe in deeply. The sweet air fills your lungs and you sigh, contemptness filling you. It's sunny and warm out, a cool breeze ruffling the leaves on the nearby trees.")
print("You open your eyes and look around, taking in all of the vibrant colors. The grass is a bright green below you, the sky a shining blue above you. A few white, puffy clouds float along the sky.")
print("It's a beautiful day out, but yo have absolutely nothing to do. That makes you even happier. You got a day off today, and decided to pack a few things in a bag and drive over to the field you live by.")
print("It's hard to find if you don't know it's there. It's pretty small, maybe only a football field across in length. It's full of hills, which give people plenty of privacy. It's completely surrounded by trees and there's no path or roadleading to it.")
print("You had to leave your car in the woods. Usually there were at least a few people here, but today there were none. The field was empty and you had it all to yourself.")
print("What would you like to do first? type A if you'd like to read a book you brought, type B to lie down in the sun, or type C to wander the fields.")
user_input = input()
if user_input == "A":
    print("You pull out the book you've been reading lately and find a shady spot at the bottom of one of the hills. The air is a bit cooler here and the grass is soft beneath you. You sit and lie down, cracking open the story.")
    print("You quickly get lost in the world of adventure and forget where you are. The story seems so real, and you can practically see it happening. You read for a little while before a bird landing infront of you snaps you back to the present.")
    print("The bird cocks its head and looks at you. Do you shoo it away?")
    user_input_1 = input()
    if user_input_1 == "yes":
        print("You wiggle your leg towards it, not enough to actually hurt it but enough to scare it away. It gives out a short squack and flaps away, gaining height until all it is is a small dot on the horizon.")
    if user_input_1 == "no":
        print("You leave the bird alone and set down your book. You place it next to you and sit up, stretching your legs. The bird continues to watch you curiously. You smile at it and stand, enjoying the feeling returning to your feet.")
        print("You walk in slow circles to get your blood flowing again and notice the bird following you. You're not sure why, but it makes you feel even happier. It's like having a hidden protector suddenly be revealed.")
if user_input == "B":
    print("You go to the top of a nearby hill and lie down on the grass. The heat settles on your skin like a fine mist. The heat makes you feel tired and you close your eyes. While lying there, you can feel yourself starting to slip into sleep. Would you like to get up?")
    user_input_2 = input()
    if user_input_2 == "yes":
        print("You grogilly sit up and rub the sleep from your eyes. Though it's comfortable, you still wouldn't want to fall asleep in a random place. You stand and stretch for a little while.")
    if user_input_2 == "no":
        print("You decide it's too comfortable to pass up and allow yorself to sleep. You curl on the grass and sigh with contempt.")
        print("You wake a little while later and sit up, glancing around. You're still at the same place you were before, and nothing seems to have changed. Well, other than the suns position, that is.")
        print("You stand and stretch, feeling your muscles and joints groan in protest. Your bag is still sitting at your feet and you stoop to pick it up.")
if user_input == "C":
    print("You pick a direction and start to walk in it, simply enjoying the breeze that carries with it scents of pine trees and clean rain. The shadows on the ground move and sway as the wind blows through the leaves.")
    print("You walk along the circumference of the field, following some unseen path. Living in the city, you often forget the simple joys that nature brings. No technology could ever compare to the easy relaxation you were getting.")
    print("You wander along until your legs get sore. A few minutes later, you find your way back to the same spot you'd started in and sit.")
print("You find yourself with nothing to do. You feel a bit of boredom begin to creep in and get up, walking to the other end of the field. You'd head some stories, but never found it for yourself. Now was as good a time as any.")
print("You make a mental note of what way you're going before stepping over a small bush and into the woods. The air is fuller here, giving off earthy scents. You smile as you watch the way the leaves are casting broken shadows on the ground.")
print("You walk for a while in the same general direction. It isn't too long before you hear rushing water. You smile to yourself as the sound gets louder with every step you take. You keep following that sound until it's all you can hear.")
print("You squint forward and just barely see a constant movement through some tall shrubs. You fight your way through them and finally break through onto the other side. A river flows past you, on its way somewhere else from somewhere else.")
print("You glance around and find a bend in the river a little way up where the water is slow. You walk over and notice that it also gets pretty deep.")
print("Do you want to swim?")
user_input = input()
if user_input == "yes":
    print("You pull off your shirt and place it on the ground. You're glad you wore shorts today and you wade into the river. It's warm and still. Perfect. You go in until your stomach is covered before deciding to fully dive in.")
    print("You resurface, hair plastered to your head. You swim out a bit more until you can't touch the bottom and tire yourself out splashing in the cool water. You clamber out a while later, dripping wet and shivering.")
    print("You find the nearest patch of sun and run over to sit in it. The light warms your skin and within a few minutes, your hair and body is dry. You pull your shirt back on and decide to head back to your car.")
    print("You make sure you'll remember where this is before heading out. By the time you make it back to the field, the sun hsa started it's way back to sleep. A few long shadows  break apart the grass.")
    print("You make one last trip around the field and go back to the spot where you parked your car. You walk for a few minutes searching before you realize that you are completely lost. All of the trees look similar, and you can't remember which way you parked.")
    print("Do you want to keep looking?")
    user_input_7 = input()
    while user_input_7 != "no":
        print("you wander around a bit more, finding yourself more lost than before.")
        user_input_7 = input()
    print("You pull your keys out from your pocket and fumble with them for a second. The sun is going down and it's hard to make out the buttons. You look for the unlock button, hoping that the flash of lights will give an idea of where to go.")
    print("You press the button and scream as the car alarm starts going on directly behind you. You turn and shove through a few trees. Your car is sitting in the clearing, honking and flashing lights.")
    print("You haistily hit the button again and it falls silent. You hope there's no one around to have heard that. You hit a different button and the doors unlock. You slide in and slump behind the wheel.")
    print("You wait a second before putting the key into the ignition and feeling the car rumble to life. You slowly crawl forward, giving yourself plenty of time to stop if you need to. There's no one out on the road tonight, however, and you turn onto the road with no trouble.")
    print("You're back home a few minutes later, opening the door to your apartment. You shut it behind you and walk in, dropping your stuff as you go. You flop back onto your bed, filled with happiness. Today was a good day. A great day.")
    print("With all the stress that's been hitting you lately, it's been great to get a small break.")
    print("Do you want to get up and brush your teeth?")
    user_input_4 = input()
    if user_input_4 == "yes":
        print("You get up and walk to your bathroom. You quickly brush your teeth and splash some water in your face. You already feel better. You walk back out and flop onto bed, quickly falling asleep in the familiar bundle of blankets and pillows.")
        print("Thank you for playing our game, and always remember to be happy.")
    if user_input_4 == "no":
        print("You decide it can wait for tomorrow and instead curl up under the familiar blankets. Sleep comes easily and quickly, and soon you're enjoying the best sleep you've had in awhile.")
        print("Thank you for playing our game, and always remember to be happy.")
if user_input == "no":
    print("You decide not to swim and instead lie down on the grass, enjoying the sunlight. You stay there for a while and easily lose track of time. Before you know it, the sun begins setting and you stand, heading on the way back to the car.")
    print("You make sure you'll remember where this is before heading out. By the time you make it back to the field, the sun hsa started it's way back to sleep. A few long shadows  break apart the grass.")
    print("You make one last trip around the field and go back to the spot where you parked your car. You walk for a few minutes searching before you realize that you are completely lost. All of the trees look similar, and you can't remember which way you parked.")
    print("Do you want to keep looking?")
    user_input_5 = input()
    while user_input_5 != "no":
        print("you wander around a bit more, finding yourself more lost than before.")
        user_input_5 = input()
    print("You pull your keys out from your pocket and fumble with them for a second. The sun is going down and it's hard to make out the buttons. You look for the unlock button, hoping that the flash of lights will give an idea of where to go.")
    print("You press the button and scream as the car alarm starts going on directly behind you. You turn and shove through a few trees. Your car is sitting in the clearing, honking and flashing lights.")
    print("You haistily hit the button again and it falls silent. You hope there's no one around to have heard that. You hit a different button and the doors unlock. You slide in and slump behind the wheel.")
    print("You wait a second before putting the key into the ignition and feeling the car rumble to life. You slowly crawl forward, giving yourself plenty of time to stop if you need to. There's no one out on the road tonight, however, and you turn onto the road with no trouble.")
    print("You're back home a few minutes later, opening the door to your apartment. You shut it behind you and walk in, dropping your stuff as you go. You flop back onto your bed, filled with happiness. Today was a good day. A great day.")
    print("With all the stress that's been hitting you lately, it's been great to get a small break.")
    print("Do you want to get up and brush your teeth?")
    user_input_6 = input()
    if user_input_6 == "yes":
        print("You get up and walk to your bathroom. You quickly brush your teeth and splash some water in your face. You already feel better. You walk back out and flop onto bed, quickly falling asleep in the familiar bundle of blankets and pillows.")
        print("Thank you for playing our game, and always remember to be happy.")
    if user_input_6 == "no":
        print("You decide it can wait for tomorrow and instead curl up under the familiar blankets. Sleep comes easily and quickly, and soon you're enjoying the best sleep you've had in awhile.")
        print("Thank you for playing our game, and always remember to be happy.")
